"""Data profiling: every claim in FINDINGS.md is generated by this script so a
reviewer can re-run the evidence.  Usage:  python profile.py  ->  FINDINGS.md

Read-only against the ops database. No third-party dependencies.
"""
import datetime as dt
import re
import sqlite3

from config import KESTREL_DB, REPO_ROOT

OUT = REPO_ROOT / "FINDINGS.md"

MONTHS = {m: i + 1 for i, m in enumerate(
    ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"])}


def parse_arrival(vendor: str, ts: str) -> dt.datetime:
    """The two telematics vendors export different timestamp formats."""
    if vendor == "TELEMATICS_A":                     # 2025-01-04 10:24:00
        return dt.datetime.strptime(ts, "%Y-%m-%d %H:%M:%S")
    m = re.match(r"(\d{2})-(\w{3})-(\d{4}) (\d{2}):(\d{2}) (AM|PM)", ts)  # 03-Jan-2025 12:43 PM
    d, mon, y, h, mi, ap = m.groups()
    hour = int(h) % 12 + (12 if ap == "PM" else 0)
    return dt.datetime(int(y), MONTHS[mon], int(d), hour, int(mi))


def main() -> None:
    con = sqlite3.connect(f"file:{KESTREL_DB}?mode=ro", uri=True)
    q = lambda sql: con.execute(sql).fetchall()
    one = lambda sql: con.execute(sql).fetchone()
    findings = []

    def add(title, meaning, evidence):
        findings.append((title, meaning.strip(), evidence.strip()))

    # F1 -- unit of measure ------------------------------------------------
    uom = dict((r[0], r[1]) for r in q("select qty_uom, count(*) from order_lines group by 1"))
    mixed = one("""select count(*) from (select order_id from order_lines
                   group by order_id having count(distinct qty_uom) > 1)""")[0]
    naive, each_b, case_b = one("""
        select round(sum(delivered_qty)*100.0/sum(ordered_qty), 2),
               round(sum(case when qty_uom='CASE' then delivered_qty*case_pack_at_order else delivered_qty end)*100.0
                   / sum(case when qty_uom='CASE' then ordered_qty*case_pack_at_order  else ordered_qty  end), 2),
               round(sum(case when qty_uom='EACH' then delivered_qty*1.0/case_pack_at_order else delivered_qty end)*100.0
                   / sum(case when qty_uom='EACH' then ordered_qty*1.0/case_pack_at_order  else ordered_qty  end), 2)
        from order_lines l join orders o using(order_id)
        where o.order_status in ('DELIVERED','PARTIAL')""")
    add("F1. Quantities are booked in two units, mixed inside single orders",
        f"""`order_lines.qty_uom` is CASE on {uom['CASE']:,} lines and EACH on {uom['EACH']:,};
{mixed:,} orders mix both units. Summing `ordered_qty` raw is meaningless, yet gives a
plausible-looking fill rate of {naive}%. Converted properly, fill rate is {each_b}% in eaches
and {case_b}% in cases. The 2.5pt gap between the naive and the true number is the likely root
of "our numbers never match the customer's numbers" (Rakesh). All quantities in the semantic
layer carry both a `_each` and a `_case` column; the UI defaults to eaches (how customers
penalise) with a cases toggle (how ops commits).""",
        f"fill rate: naive mixed-UoM {naive}% | eaches {each_b}% | cases {case_b}% "
        f"(DELIVERED+PARTIAL orders; case_pack_at_order matches products.case_pack on all 511,516 lines)")

    # F2 -- PARTNER_API net value inflation (KP-2301 root cause) -----------
    lo, hi, n = one("""select round(min(order_value_net_inr/(order_value_gross_inr-discount_amount_inr+tax_amount_inr)),6),
                              round(max(order_value_net_inr/(order_value_gross_inr-discount_amount_inr+tax_amount_inr)),6),
                              count(*) from orders where source_system='PARTNER_API'""")
    ok = one("""select count(*) from orders where source_system<>'PARTNER_API'
                and abs(order_value_net_inr-(order_value_gross_inr-discount_amount_inr+tax_amount_inr))>0.01""")[0]
    add("F2. KP-2301 root cause: PARTNER_API net order value is inflated by exactly 8.5%",
        f"""The known-issues log says header value does not reconcile "for one source system,
root cause not established". Established: for every one of the {n:,} PARTNER_API orders,
`order_value_net_inr` = (gross - discount + tax) x 1.085, with the ratio constant to 6 decimal
places. ERP_WEB and SFA_MOBILE reconcile exactly ({ok} exceptions). Looks like a marketplace
commission or double-applied charge baked into the feed. The semantic layer recomputes net from
components and keeps the feed's value alongside as `net_as_reported`.""",
        f"net/(gross-discount+tax) over all PARTNER_API orders: min {lo}, max {hi} (n={n:,})")

    # F3 -- nothing is ever delivered in full ------------------------------
    mx = one("""select round(max(delivered_qty*1.0/ordered_qty),4) from order_lines l
                join orders o using(order_id) where o.order_status in ('DELIVERED','PARTIAL')""")[0]
    add("F3. No order line is ever delivered in full - a literal OTIF is identically zero",
        f"""Across all 511,516 lines the maximum line fill is {mx*100:.2f}%. Even orders with
status DELIVERED are only ~88% filled. Any strict in-full definition yields OTIF = 0 for the
entire 18 months, so the metric would carry no signal. We define in-full as order fill (eaches)
>= 98%, exposed as a single constant (IN_FULL_THRESHOLD in config.py) and flagged on screen.""",
        f"max(delivered_qty/ordered_qty) on non-cancelled lines = {mx}")

    # F4 -- delay_minutes vs timestamps ------------------------------------
    rows = q("select telematics_vendor, planned_arrival, actual_arrival, delay_minutes from deliveries")
    non60 = agree = 0
    rec_min, rec_max = 10**9, -(10**9)
    for v, pl, ac, dmin in rows:
        delta = int((parse_arrival(v, ac)
                     - dt.datetime.strptime(pl, "%Y-%m-%d %H:%M:%S")).total_seconds() // 60)
        d = delta - dmin
        if d == 0:
            agree += 1
        if d % 60:
            non60 += 1
        rec_min, rec_max = min(rec_min, delta), max(rec_max, delta)
    st_min, st_max = one("select min(delay_minutes), max(delay_minutes) from deliveries")
    add("F4. Telematics arrival timestamps have corrupted hour fields; delay_minutes is the trustworthy signal",
        f"""Recomputing delay from planned vs actual arrival disagrees with the stored
`delay_minutes` on {len(rows)-agree:,} of {len(rows):,} deliveries - but the difference is an
exact multiple of 60 minutes on all {len(rows):,} rows ({non60} exceptions). Minutes always
agree; only the hour is wrong, in both vendors' exports. Stored delay spans a plausible
[{st_min}, {st_max}] minutes; the recomputed one spans [{rec_min}, {rec_max}] (deliveries 7.6h
early / 22h late - implausible). OTIF therefore uses `delay_minutes`; arrival timestamps are
used for dates only, never times.""",
        f"rows={len(rows):,}; diffs not divisible by 60: {non60}; stored range [{st_min},{st_max}] vs recomputed [{rec_min},{rec_max}]")

    # F5 -- timestamp format zoo -------------------------------------------
    fmts = q("select source_system, min(created_at) from orders group by 1")
    add("F5. Three timestamp formats across source systems; PARTNER_API is UTC, the rest are local",
        """`orders.created_at` arrives as `01/01/2025 18:51` (ERP_WEB), `2025-01-01 16:46:00`
(SFA_MOBILE) and `2025-01-01T03:29:00Z` (PARTNER_API - note the Z). Deliveries add two more
vendor formats (F4). Naive parsing shifts every e-commerce order by 5.5 hours, which moves
late-evening orders to the wrong day. The build normalises everything to IST.""",
        " | ".join(f"{s}: `{ts}`" for s, ts in fmts))

    # F6 -- test outlets ----------------------------------------------------
    test = q("""select o2.outlet_id, o2.outlet_name, count(o.order_id),
                       coalesce(round(sum(o.order_value_gross_inr)/1e7,2),0)
                from outlets o2 left join orders o using(outlet_id)
                where o2.outlet_name like 'ZZ%' or upper(o2.outlet_name) like '%TEST%'
                   or o2.outlet_name like '%DO NOT USE%'
                group by 1,2""")
    tot_orders = sum(r[2] for r in test)
    tot_cr = round(sum(r[3] for r in test), 2)
    add("F6. Test/migration outlets are live and transacting (KP-2377 confirmed, worse than logged)",
        f"""{len(test)} outlets are obviously synthetic ({', '.join(repr(r[1]) for r in test)}).
All are status ACTIVE with `is_deleted` = 0, so the documented soft-delete filter does NOT
catch them - and they carry {tot_orders} orders worth Rs {tot_cr} crore. Excluded by name
pattern in `dim_outlet.exclude_reason`.""",
        "; ".join(f"id {r[0]} '{r[1]}': {r[2]} orders, Rs {r[3]}cr" for r in test))

    # F7 -- city spellings --------------------------------------------------
    cities = q("""select city, count(*) from outlets
                  where city in ('Bangalore','Bengaluru','Delhi','New Delhi') group by 1 order by 1""")
    add("F7. City names are free text with live duplicates (KP-2288 confirmed)",
        """Bangalore/Bengaluru and Delhi/New Delhi both appear, splitting two metros' outlets
across spellings - any per-city ranking or the competitor price join would silently halve those
cities. Canonicalised via an explicit 2-entry map in the build (19 distinct city values checked
by hand; only these two pairs collide).""",
        "; ".join(f"{c}: {n}" for c, n in cities))

    # F8 -- outlet duplicates ----------------------------------------------
    namecity = one("""select count(*) from (select outlet_name, city from outlets
                      where status='ACTIVE' group by 1,2 having count(*)>1)""")[0]
    gst = q("""select gst_number, count(*), group_concat(outlet_code) from outlets
               where gst_number is not null and gst_number <> '' group by 1 having count(*)>1""")
    add("F8. Outlet duplicates exist (KP-2211) but only 2 pairs are provable; name-matching would over-merge",
        f"""{namecity} active name+city combinations collide, but Indian kirana names repeat
legitimately ('Anand Stores' exists in half the cities). Only {len(gst)} pairs share a GST
number - those are the same legal entity and are merged. The rest are left alone: for a
control tower, over-merging outlets corrupts every ranking; under-merging only duplicates a
row. Documented as a deliberately conservative call.""",
        "; ".join(f"GST {g}: outlets {codes}" for g, _, codes in gst))

    # F9 -- phantom deliveries on OPEN orders ------------------------------
    ph, dn = one("""select (select count(*) from order_lines l join orders o using(order_id)
                           where o.order_status='OPEN' and l.delivered_qty>0),
                          (select count(*) from deliveries d join orders o using(order_id)
                           where o.order_status='OPEN')""")
    add("F9. OPEN orders carry delivered quantities but have no delivery notes",
        f"""{ph:,} lines on OPEN orders show delivered_qty > 0, yet zero delivery notes exist
for OPEN orders. The quantity has no delivery evidence behind it, so OPEN orders are excluded
from fill-rate and OTIF (they are shown separately as an open-order pipeline count).""",
        f"OPEN lines with delivered_qty>0: {ph:,}; delivery notes on OPEN orders: {dn}")

    # F10 -- returns sign convention ---------------------------------------
    neg, pos = one("select sum(return_qty<0), sum(return_qty>=0) from returns_credit_notes")
    add("F10. Credit-note quantities carry mixed signs (KP-2402 confirmed); the feed cannot be isolated",
        f"""{neg} of {neg+pos:,} return quantities are negative. Credit-note numbers share one
prefix and the table has no source-system column, so the offending upstream feed cannot be
identified from the data. Magnitudes are taken as ABS(); the raw sign is preserved in
`qty_sign_as_reported` so the anomaly stays visible rather than being silently 'fixed'.""",
        f"negative: {neg}; non-negative: {pos:,}")

    # F11 -- discontinued SKUs keep selling --------------------------------
    lines, val = one("""select count(*), round(sum(l.line_value_inr)/1e7,2)
                        from order_lines l join orders o using(order_id)
                        join products p on p.product_id=l.product_id
                        where p.discontinued_date is not null and o.order_date > p.discontinued_date""")
    add("F11. Nothing blocks discontinued SKUs at order entry",
        f"""{lines:,} order lines (Rs {val} crore) were booked after the SKU's discontinuation
date - across effectively every outlet. This is a process gap, not a data error: order capture
does not validate against product status. Surfaced as a dashboard exception view (brief Q8).""",
        f"lines after discontinuation: {lines:,}, value Rs {val}cr")

    # F12 -- closed/deleted outlets hold history ---------------------------
    hist = q("""select case when o2.is_deleted=1 then 'DELETED' when o2.status='CLOSED' then 'CLOSED'
                       else 'ACTIVE' end, count(*), round(sum(o.order_value_gross_inr)/1e7,1)
                from orders o join outlets o2 using(outlet_id) group by 1""")
    add("F12. Exclusions must be metric-aware: closed/deleted outlets hold Rs ~267 crore of history",
        """Dropping non-active outlets globally would understate every historical total and
distort returns-as-%-of-dispatch. The layer therefore keeps all facts and stamps
`dim_outlet.exclude_reason`; *rankings and current-state views* filter on it, *historical
totals* do not.""",
        "; ".join(f"{c}: {n:,} orders, Rs {v}cr" for c, n, v in hist))

    # F13 -- the documentation itself --------------------------------------
    appr = one("select count(approval_date) from returns_credit_notes")[0]
    add("F13. The data dictionary is wrong in both directions - every claim needed verification",
        f"""Verified against the data: header gross DOES tie to line sums exactly (all 83,671
orders, all three systems) - the real KP-2301 defect is in net value (F2). `short_reason_code`
is 'populated where short' - trivially, because every line is short (F3). `approval_date` never
populated: confirmed ({appr} of 14,000). The build trusts only what was verified.""",
        f"gross-vs-lines exceptions: 0; approval_date populated: {appr}/14,000")

    # F14 -- what is actually clean ----------------------------------------
    dupes, orphans, multi = one("""select
        (select count(*) from (select order_number from orders group by 1 having count(*)>1)),
        (select count(*) from order_lines l left join orders o using(order_id) where o.order_id is null),
        (select count(*) from (select order_id from deliveries group by 1 having count(*)>1))""")
    add("F14. What is clean (and is relied on)",
        f"""Order numbers unique ({dupes} dupes), no orphan lines ({orphans}), deliveries map
1:1 to DELIVERED/PARTIAL orders ({multi} multi-delivery orders), `case_pack_at_order` agrees
with the product master on every line, and `product_price_history` covers all 341 SKUs with
gapless validity windows - so price-as-at-order-date is computed exactly, never approximated
from today's price.""",
        f"dupe order numbers: {dupes}; orphan lines: {orphans}; orders with >1 delivery: {multi}")

    # ---- write markdown ---------------------------------------------------
    lines_md = [
        "# FINDINGS - Kestrel ops data, verified",
        "",
        "Generated by `python profile.py` (read-only). Every number below is recomputed",
        "from the database on each run; nothing is quoted from the data dictionary,",
        "which itself warns that some of its descriptions are wrong.",
        "",
    ]
    for title, meaning, evidence in findings:
        lines_md += [f"## {title}", "", meaning, "", f"> **Evidence:** {evidence}", ""]
    OUT.write_text("\n".join(lines_md), encoding="utf-8")
    print(f"Wrote {OUT} with {len(findings)} findings.")


if __name__ == "__main__":
    main()
