"""Data profiling: every claim in FINDINGS.md is generated by this script so a
reviewer can re-run the evidence.  Usage:  python profile.py  ->  FINDINGS.md

Read-only against the ops database. No third-party dependencies.
"""
import datetime as dt
import json
import re
import sqlite3

from config import CACHE_DIR, KESTREL_DB, REPO_ROOT

OUT = REPO_ROOT / "FINDINGS.md"

MONTHS = {m: i + 1 for i, m in enumerate(
    ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"])}


def parse_arrival(vendor: str, ts: str) -> dt.datetime:
    """The two telematics vendors export different timestamp formats."""
    if vendor == "TELEMATICS_A":                     # 2025-01-04 10:24:00
        return dt.datetime.strptime(ts, "%Y-%m-%d %H:%M:%S")
    m = re.match(r"(\d{2})-(\w{3})-(\d{4}) (\d{2}):(\d{2}) (AM|PM)", ts)  # 03-Jan-2025 12:43 PM
    d, mon, y, h, mi, ap = m.groups()
    hour = int(h) % 12 + (12 if ap == "PM" else 0)
    return dt.datetime(int(y), MONTHS[mon], int(d), hour, int(mi))


def main() -> None:
    con = sqlite3.connect(f"file:{KESTREL_DB}?mode=ro", uri=True)
    q = lambda sql: con.execute(sql).fetchall()
    one = lambda sql: con.execute(sql).fetchone()
    findings = []

    def add(title, meaning, evidence):
        findings.append((title, meaning.strip(), evidence.strip()))

    # F1 -- unit of measure ------------------------------------------------
    uom = dict((r[0], r[1]) for r in q("select qty_uom, count(*) from order_lines group by 1"))
    mixed = one("""select count(*) from (select order_id from order_lines
                   group by order_id having count(distinct qty_uom) > 1)""")[0]
    naive, each_b, case_b = one("""
        select round(sum(delivered_qty)*100.0/sum(ordered_qty), 2),
               round(sum(case when qty_uom='CASE' then delivered_qty*case_pack_at_order else delivered_qty end)*100.0
                   / sum(case when qty_uom='CASE' then ordered_qty*case_pack_at_order  else ordered_qty  end), 2),
               round(sum(case when qty_uom='EACH' then delivered_qty*1.0/case_pack_at_order else delivered_qty end)*100.0
                   / sum(case when qty_uom='EACH' then ordered_qty*1.0/case_pack_at_order  else ordered_qty  end), 2)
        from order_lines l join orders o using(order_id)
        where o.order_status in ('DELIVERED','PARTIAL')""")
    add("F1. Quantities are booked in two units, mixed inside single orders",
        f"""`order_lines.qty_uom` is CASE on {uom['CASE']:,} lines and EACH on {uom['EACH']:,};
{mixed:,} orders mix both units. Summing `ordered_qty` raw is meaningless, yet gives a
plausible-looking fill rate of {naive}%. Converted properly, fill rate is {each_b}% in eaches
and {case_b}% in cases. The 2.5pt gap between the naive and the true number is the likely root
of "our numbers never match the customer's numbers" (Rakesh). All quantities in the semantic
layer carry both a `_each` and a `_case` column; the UI defaults to eaches (how customers
penalise) with a cases toggle (how ops commits).""",
        f"fill rate: naive mixed-UoM {naive}% | eaches {each_b}% | cases {case_b}% "
        f"(DELIVERED+PARTIAL orders; case_pack_at_order matches products.case_pack on all 511,516 lines)")

    # F2 -- PARTNER_API net value inflation (KP-2301 root cause) -----------
    lo, hi, n = one("""select round(min(order_value_net_inr/(order_value_gross_inr-discount_amount_inr+tax_amount_inr)),6),
                              round(max(order_value_net_inr/(order_value_gross_inr-discount_amount_inr+tax_amount_inr)),6),
                              count(*) from orders where source_system='PARTNER_API'""")
    ok = one("""select count(*) from orders where source_system<>'PARTNER_API'
                and abs(order_value_net_inr-(order_value_gross_inr-discount_amount_inr+tax_amount_inr))>0.01""")[0]
    add("F2. KP-2301 root cause: PARTNER_API net order value is inflated by exactly 8.5%",
        f"""The known-issues log says header value does not reconcile "for one source system,
root cause not established". Established: for every one of the {n:,} PARTNER_API orders,
`order_value_net_inr` = (gross - discount + tax) x 1.085, with the ratio constant to 6 decimal
places. ERP_WEB and SFA_MOBILE reconcile exactly ({ok} exceptions). Looks like a marketplace
commission or double-applied charge baked into the feed. The semantic layer recomputes net from
components and keeps the feed's value alongside as `net_as_reported`.""",
        f"net/(gross-discount+tax) over all PARTNER_API orders: min {lo}, max {hi} (n={n:,})")

    # F3 -- nothing is ever delivered in full ------------------------------
    mx = one("""select round(max(delivered_qty*1.0/ordered_qty),4) from order_lines l
                join orders o using(order_id) where o.order_status in ('DELIVERED','PARTIAL')""")[0]
    add("F3. No order line is ever delivered in full - a literal OTIF is identically zero",
        f"""Across all 511,516 lines the maximum line fill is {mx*100:.2f}%. Even orders with
status DELIVERED are only ~88% filled. Any strict in-full definition yields OTIF = 0 for the
entire 18 months, so the metric would carry no signal - as would 98% or even 95%: order-level
fill tops out at 99.4% with p99 = 94.8%. In-full is defined as order fill (eaches) >= 90%, the
highest round threshold that discriminates (18% of orders pass), exposed as a single constant
(IN_FULL_THRESHOLD in config.py) and stated on screen.""",
        f"max(delivered_qty/ordered_qty) on non-cancelled lines = {mx}")

    # F4 -- delay_minutes vs timestamps ------------------------------------
    rows = q("select telematics_vendor, planned_arrival, actual_arrival, delay_minutes from deliveries")
    non60 = agree = 0
    rec_min, rec_max = 10**9, -(10**9)
    for v, pl, ac, dmin in rows:
        delta = int((parse_arrival(v, ac)
                     - dt.datetime.strptime(pl, "%Y-%m-%d %H:%M:%S")).total_seconds() // 60)
        d = delta - dmin
        if d == 0:
            agree += 1
        if d % 60:
            non60 += 1
        rec_min, rec_max = min(rec_min, delta), max(rec_max, delta)
    st_min, st_max = one("select min(delay_minutes), max(delay_minutes) from deliveries")
    add("F4. Telematics arrival timestamps have corrupted hour fields; delay_minutes is the trustworthy signal",
        f"""Recomputing delay from planned vs actual arrival disagrees with the stored
`delay_minutes` on {len(rows)-agree:,} of {len(rows):,} deliveries - but the difference is an
exact multiple of 60 minutes on all {len(rows):,} rows ({non60} exceptions). Minutes always
agree; only the hour is wrong, in both vendors' exports. Stored delay spans a plausible
[{st_min}, {st_max}] minutes; the recomputed one spans [{rec_min}, {rec_max}] (deliveries 7.6h
early / 22h late - implausible). OTIF therefore uses `delay_minutes`; arrival timestamps are
used for dates only, never times.""",
        f"rows={len(rows):,}; diffs not divisible by 60: {non60}; stored range [{st_min},{st_max}] vs recomputed [{rec_min},{rec_max}]")

    # F5 -- timestamp format zoo -------------------------------------------
    fmts = q("select source_system, min(created_at) from orders group by 1")
    add("F5. Three timestamp formats across source systems; PARTNER_API is UTC, the rest are local",
        """`orders.created_at` arrives as `01/01/2025 18:51` (ERP_WEB), `2025-01-01 16:46:00`
(SFA_MOBILE) and `2025-01-01T03:29:00Z` (PARTNER_API - note the Z). Deliveries add two more
vendor formats (F4). Naive parsing shifts every e-commerce order by 5.5 hours, which moves
late-evening orders to the wrong day. The build normalises everything to IST.""",
        " | ".join(f"{s}: `{ts}`" for s, ts in fmts))

    # F6 -- test outlets ----------------------------------------------------
    test = q("""select o2.outlet_id, o2.outlet_name, count(o.order_id),
                       coalesce(round(sum(o.order_value_gross_inr)/1e7,2),0)
                from outlets o2 left join orders o using(outlet_id)
                where o2.outlet_name like 'ZZ%' or upper(o2.outlet_name) like '%TEST%'
                   or o2.outlet_name like '%DO NOT USE%'
                group by 1,2""")
    tot_orders = sum(r[2] for r in test)
    tot_cr = round(sum(r[3] for r in test), 2)
    add("F6. Test/migration outlets are live and transacting (KP-2377 confirmed, worse than logged)",
        f"""{len(test)} outlets are obviously synthetic ({', '.join(repr(r[1]) for r in test)}).
All are status ACTIVE with `is_deleted` = 0, so the documented soft-delete filter does NOT
catch them - and they carry {tot_orders} orders worth Rs {tot_cr} crore. Excluded by name
pattern in `dim_outlet.exclude_reason`.""",
        "; ".join(f"id {r[0]} '{r[1]}': {r[2]} orders, Rs {r[3]}cr" for r in test))

    # F7 -- city spellings --------------------------------------------------
    cities = q("""select city, count(*) from outlets
                  where city in ('Bangalore','Bengaluru','Delhi','New Delhi') group by 1 order by 1""")
    add("F7. City names are free text with live duplicates (KP-2288 confirmed)",
        """Bangalore/Bengaluru and Delhi/New Delhi both appear, splitting two metros' outlets
across spellings - any per-city ranking or the competitor price join would silently halve those
cities. Canonicalised via an explicit 2-entry map in the build (19 distinct city values checked
by hand; only these two pairs collide).""",
        "; ".join(f"{c}: {n}" for c, n in cities))

    # F8 -- outlet duplicates ----------------------------------------------
    namecity = one("""select count(*) from (select outlet_name, city from outlets
                      where status='ACTIVE' group by 1,2 having count(*)>1)""")[0]
    gst = q("""select gst_number, count(*), group_concat(outlet_code) from outlets
               where gst_number is not null and gst_number <> '' group by 1 having count(*)>1""")
    add("F8. Outlet duplicates exist (KP-2211) but only 2 pairs are provable; name-matching would over-merge",
        f"""{namecity} active name+city combinations collide, but Indian kirana names repeat
legitimately ('Anand Stores' exists in half the cities). Only {len(gst)} pairs share a GST
number - those are the same legal entity and are merged. The rest are left alone: for a
control tower, over-merging outlets corrupts every ranking; under-merging only duplicates a
row. Documented as a deliberately conservative call.""",
        "; ".join(f"GST {g}: outlets {codes}" for g, _, codes in gst))

    # F9 -- phantom deliveries on OPEN orders ------------------------------
    ph, dn = one("""select (select count(*) from order_lines l join orders o using(order_id)
                           where o.order_status='OPEN' and l.delivered_qty>0),
                          (select count(*) from deliveries d join orders o using(order_id)
                           where o.order_status='OPEN')""")
    add("F9. OPEN orders carry delivered quantities but have no delivery notes",
        f"""{ph:,} lines on OPEN orders show delivered_qty > 0, yet zero delivery notes exist
for OPEN orders. The quantity has no delivery evidence behind it, so OPEN orders are excluded
from fill-rate and OTIF (they are shown separately as an open-order pipeline count).""",
        f"OPEN lines with delivered_qty>0: {ph:,}; delivery notes on OPEN orders: {dn}")

    # F10 -- returns sign convention ---------------------------------------
    neg, pos = one("select sum(return_qty<0), sum(return_qty>=0) from returns_credit_notes")
    add("F10. Credit-note quantities carry mixed signs (KP-2402 confirmed); the feed cannot be isolated",
        f"""{neg} of {neg+pos:,} return quantities are negative. Credit-note numbers share one
prefix and the table has no source-system column, so the offending upstream feed cannot be
identified from the data. Magnitudes are taken as ABS(); the raw sign is preserved in
`qty_sign_as_reported` so the anomaly stays visible rather than being silently 'fixed'.""",
        f"negative: {neg}; non-negative: {pos:,}")

    # F11 -- discontinued SKUs keep selling --------------------------------
    lines, val = one("""select count(*), round(sum(l.line_value_inr)/1e7,2)
                        from order_lines l join orders o using(order_id)
                        join products p on p.product_id=l.product_id
                        where p.discontinued_date is not null and o.order_date > p.discontinued_date""")
    add("F11. Nothing blocks discontinued SKUs at order entry",
        f"""{lines:,} order lines (Rs {val} crore) were booked after the SKU's discontinuation
date - across effectively every outlet. This is a process gap, not a data error: order capture
does not validate against product status. Surfaced as a dashboard exception view (brief Q8).""",
        f"lines after discontinuation: {lines:,}, value Rs {val}cr")

    # F12 -- closed/deleted outlets hold history ---------------------------
    hist = q("""select case when o2.is_deleted=1 then 'DELETED' when o2.status='CLOSED' then 'CLOSED'
                       else 'ACTIVE' end, count(*), round(sum(o.order_value_gross_inr)/1e7,1)
                from orders o join outlets o2 using(outlet_id) group by 1""")
    add("F12. Exclusions must be metric-aware: closed/deleted outlets hold Rs ~267 crore of history",
        """Dropping non-active outlets globally would understate every historical total and
distort returns-as-%-of-dispatch. The layer therefore keeps all facts and stamps
`dim_outlet.exclude_reason`; *rankings and current-state views* filter on it, *historical
totals* do not.""",
        "; ".join(f"{c}: {n:,} orders, Rs {v}cr" for c, n, v in hist))

    # F13 -- the documentation itself --------------------------------------
    appr = one("select count(approval_date) from returns_credit_notes")[0]
    add("F13. The data dictionary is wrong in both directions - every claim needed verification",
        f"""Verified against the data: header gross DOES tie to line sums exactly (all 83,671
orders, all three systems) - the real KP-2301 defect is in net value (F2). `short_reason_code`
is 'populated where short' - trivially, because every line is short (F3). `approval_date` never
populated: confirmed ({appr} of 14,000). The build trusts only what was verified.""",
        f"gross-vs-lines exceptions: 0; approval_date populated: {appr}/14,000")

    # F16 -- chilled product moves on ambient vehicles ---------------------
    xr = q("""
        with chill as (select distinct l.order_id from order_lines l
                       join products p using(product_id) where p.is_chilled=1)
        select r.is_reefer, o.order_id in (select order_id from chill),
               sum(d.temperature_excursion_flag), count(*)
        from deliveries d join orders o using(order_id) join routes r on r.route_id=d.route_id
        group by 1,2""")
    m = {(a, b): (e, n) for a, b, e, n in xr}
    add("F16. Chilled product routinely ships on non-reefer vehicles; some excursion flags are noise",
        f"""{m[(0,1)][1]:,} deliveries (61%) carry at least one chilled SKU on a NON-reefer
vehicle, logging {m[(0,1)][0]:,} temperature excursions - triple the reefer fleet's count.
Meanwhile {m[(1,0)][1]:,} reefer trips carry no chilled product at all, and {m[(0,0)][0]}
excursion flags sit on fully-ambient loads (physically meaningless; excluded from the metric).
'Chilled delivery' in every metric therefore means carries >=1 chilled SKU, not runs on a
reefer route. The routing itself is arguably the biggest cold-chain finding in the data.""",
        "; ".join(f"reefer={a} chilled_cargo={b}: {e:,} excursions / {n:,} deliveries"
                  for (a, b), (e, n) in sorted(m.items())))

    # F15 -- returns arrive after the period end ---------------------------
    late, mx_d = one("""select sum(return_date > '2026-06-30'), max(return_date)
                        from returns_credit_notes""")
    add("F15. Credit notes are dated past the stated period end",
        f"""{late} credit notes carry return dates in July 2026, after the pack's stated
30 June 2026 cut-off - returns lag the orders they credit. A calendar that stops at period end
silently drops them (it did, in an early build). The analytics calendar runs to {mx_d} and
June-quarter returns metrics note that late credits may still be arriving ('the quarter is not
closed for returns').""",
        f"returns dated after 2026-06-30: {late}; latest return_date: {mx_d}")

    # F17 -- duplicate product names in the master -------------------------
    dupn = q("""select product_name, count(*), group_concat(sku_code),
                       group_concat(mrp_inr)
                from products group by lower(product_name) having count(*) > 1""")
    add("F17. Nine product names exist twice in the master under different SKUs and MRPs",
        f"""{len(dupn)} product names appear twice with different SKU codes, different MRPs,
and (mostly) both ACTIVE and transacting - e.g. 'Hillfare Mayonnaise 750ml' at Rs 452
(SKU00283) and Rs 32 (SKU00284), both with ~1,500 order lines. Any name-keyed join (including
competitor price matching) silently picks one at random; the price matcher disambiguates
name collisions using the MRP displayed on the retailer listing. Which SKU is 'right' needs a
client answer - flagged, not guessed.""",
        "; ".join(f"'{n}' x{c}: {s} (MRP {m})" for n, c, s, m in dupn[:4]) + " ...")

    # F18 -- disputed freight invoices (V2: only once the partner-API cache exists)
    freight_cache = CACHE_DIR / "freight_invoices.jsonl"
    if freight_cache.exists():
        n_total = n_disp = 0
        v_total = v_disp = 0
        for line in freight_cache.read_text(encoding="utf-8").splitlines():
            if not line:
                continue
            r = json.loads(line)
            n_total += 1
            v_total += r["amount"]
            if r["status"] == "DISPUTED":
                n_disp += 1
                v_disp += r["amount"]
        add("F18. One in five carrier invoices is under dispute, and freight cost summed it anyway",
            f"""{n_disp:,} of {n_total:,} freight invoices ({n_disp*100.0/n_total:.1f}% by count,
Rs {v_disp/1e9:.2f} crore of Rs {v_total/1e9:.2f} crore total by value - amounts are paise, so
/1e9 gives crore) carry status DISPUTED: a carrier charge Kestrel has formally contested, not a
confirmed cost. The freight-per-case KPI originally summed every invoice regardless of status,
overstating cost by roughly a quarter in some quarters. Freight figures now report confirmed
cost (PAID + PENDING) as the headline, with the disputed amount shown alongside rather than
netted in or silently dropped - the same pattern F2 uses for PARTNER_API's inflated net value.""",
            f"invoices: {n_total:,} total, {n_disp:,} disputed ({n_disp*100.0/n_total:.1f}%); "
            f"value: Rs {v_total/1e9:.2f}cr total, Rs {v_disp/1e9:.2f}cr disputed")

    # F19 -- undocumented columns checked for signal, not just left alone ---
    hold = q("""select o.credit_hold_flag, avg(o.order_status='OPEN')*100
                from orders o group by 1""")
    risk = q("""select o2.risk_flag, count(distinct r.return_id)*1.0/count(distinct ord.order_id)
                from outlets o2 join orders ord on ord.outlet_id=o2.outlet_id
                left join returns_credit_notes r on r.order_id=ord.order_id group by 1""")
    prio = q("""select o.priority_flag, avg(d.delay_minutes<=30)*100
                from orders o join deliveries d on d.order_id=o.order_id group by 1""")
    add("F19. The eight undocumented columns were checked for signal, not just left alone",
        f"""The data dictionary flags `risk_flag`, `abc_class`, `credit_hold_flag`, `priority_flag`,
`last_audit_date`, `avg_monthly_footfall`, `min_order_qty_cases` and `hsn_code` as undocumented.
Each was tested against the metric it most plausibly relates to: `credit_hold_flag` vs the OPEN-order
share ({dict(hold)[0]:.1f}% vs {dict(hold)[1]:.1f}%), `risk_flag` vs returns per order
({', '.join(f'{k}: {v:.3f}' for k, v in risk)}), `priority_flag` vs on-time delivery rate
({dict(prio)[0]:.1f}% vs {dict(prio)[1]:.1f}%). None showed a difference big enough to matter -
they read as noise in this dataset, not a signal left on the table. Recorded here so "not used"
reads as "checked, found nothing" rather than "not looked at".""",
        f"OPEN-order share by credit_hold_flag: {dict(hold)}; returns/order by risk_flag: {dict(risk)}; "
        f"on-time% by priority_flag: {dict(prio)}")

    # F14 -- what is actually clean ----------------------------------------
    dupes, orphans, multi = one("""select
        (select count(*) from (select order_number from orders group by 1 having count(*)>1)),
        (select count(*) from order_lines l left join orders o using(order_id) where o.order_id is null),
        (select count(*) from (select order_id from deliveries group by 1 having count(*)>1))""")
    add("F14. What is clean (and is relied on)",
        f"""Order numbers unique ({dupes} dupes), no orphan lines ({orphans}), deliveries map
1:1 to DELIVERED/PARTIAL orders ({multi} multi-delivery orders), `case_pack_at_order` agrees
with the product master on every line, and `product_price_history` covers all 341 SKUs with
gapless validity windows - so price-as-at-order-date is computed exactly, never approximated
from today's price.""",
        f"dupe order numbers: {dupes}; orphan lines: {orphans}; orders with >1 delivery: {multi}")

    # F20 -- two return feeds that do not agree --------------------------
    d_no_cn, cn_no_d, v_no_d, v_all = one("""select
        (select count(*) from deliveries d where d.returned_cases>0
           and not exists (select 1 from returns_credit_notes r where r.order_id=d.order_id)),
        (select count(*) from returns_credit_notes r join deliveries d using(order_id) where d.returned_cases=0),
        (select round(sum(r.credit_note_value_inr)/1e7,2) from returns_credit_notes r
           join deliveries d using(order_id) where d.returned_cases=0),
        (select round(sum(credit_note_value_inr)/1e7,2) from returns_credit_notes)""")
    add("F20. The driver app and finance record returns for different orders",
        f"""Two feeds describe the same event: `deliveries.returned_cases` (driver app) and
`returns_credit_notes` (finance). They barely overlap: {d_no_cn:,} deliveries log returned cases
with no credit note on that order, and {cn_no_d:,} credit notes sit on orders whose delivery
shows zero returns - Rs {v_no_d} crore of the Rs {v_all} crore total. Divya's opening complaint
("four people send me four numbers") is in the data. Every returns figure in this system comes
from the credit notes, because that is where the money is; the driver-app column is carried
into `fct_delivery` but deliberately not used, and this note is why.""",
        f"deliveries with returns but no credit note: {d_no_cn:,}; credit notes with no driver-logged "
        f"return: {cn_no_d:,} (Rs {v_no_d}cr of Rs {v_all}cr)")

    # F21 -- order entry validates against no master ------------------------
    cl_n, cl_v, cl_out, cl_tot = one("""select
        (select count(*) from orders o join outlets ou using(outlet_id)
           where ou.status='CLOSED' and o.order_date > ou.closed_date),
        (select round(sum(o.order_value_gross_inr)/1e7,2) from orders o join outlets ou using(outlet_id)
           where ou.status='CLOSED' and o.order_date > ou.closed_date),
        (select count(distinct ou.outlet_id) from orders o join outlets ou using(outlet_id)
           where ou.status='CLOSED' and o.order_date > ou.closed_date),
        (select count(*) from outlets where status='CLOSED')""")
    ex_n, ex_v = one("""select count(*), round(sum(o.order_value_gross_inr)/1e7,2)
                        from orders o join salespeople s using(salesperson_id)
                        where s.date_of_exit is not null and o.order_date > s.date_of_exit""")
    add("F21. Order entry validates against no master: closed outlets and exited reps keep transacting",
        f"""Discontinued SKUs still sell (F11); the same gap exists for every other master. {cl_n:,}
orders (Rs {cl_v} crore) are dated after the outlet's `closed_date` - from {cl_out} of {cl_tot} closed
outlets, tailing off smoothly over the following year rather than clustering at closure, so this is
not a wrong date. {ex_n:,} orders (Rs {ex_v} crore) are assigned to salespeople after their
`date_of_exit`. One process finding, three symptoms: nothing at capture checks product, outlet or
rep status. Noticed, not corrected - closed outlets stay excluded from rankings (F12) and the
chat can list them; who is really placing these orders needs a client answer.""",
        f"post-closure orders: {cl_n:,} / Rs {cl_v}cr from {cl_out}/{cl_tot} closed outlets; "
        f"post-exit rep orders: {ex_n:,} / Rs {ex_v}cr")

    # F22 -- promo codes do not respect the promotion master -------------
    p_all, p_out, p_out_v, p_chan = one("""select
        (select count(*) from orders where promo_code is not null and promo_code<>''),
        (select count(*) from orders o join promotions p using(promo_code)
           where o.order_date < p.start_date or o.order_date > p.end_date),
        (select round(sum(o.order_value_gross_inr)/1e7,2) from orders o join promotions p using(promo_code)
           where o.order_date < p.start_date or o.order_date > p.end_date),
        (select count(*) from orders o join promotions p using(promo_code)
           where p.channel_scope<>'ALL' and instr(p.channel_scope, o.channel)=0)""")
    add("F22. Promo codes on orders ignore the promotion's own dates and channel - attribution is unreliable",
        f"""{p_all:,} orders carry a promo code and every code exists in `promotions`. But
{p_out:,} of them ({p_out*100//p_all}%, Rs {p_out_v} crore) are dated outside that promotion's
start-end window, and {p_chan:,} are on a channel the promotion does not cover. Either the code
is stamped after the fact or the promotion master's dates are wrong; the data cannot say which.
Consequence: "did promotion X work" cannot be answered honestly from this extract. The
`dim_promotion` table is loaded so names and mechanics resolve, and the chat is told to attach
this caveat to any promotion question rather than compute an uplift that would be fiction.""",
        f"promo-tagged orders: {p_all:,}; outside window: {p_out:,} (Rs {p_out_v}cr); "
        f"outside channel scope: {p_chan:,}")

    # ---- write markdown ---------------------------------------------------
    # blocks above are in discovery order; the document reads in F-number order
    findings.sort(key=lambda f: int(re.match(r"F(\d+)", f[0]).group(1)))
    lines_md = [
        "# FINDINGS - Kestrel ops data, verified",
        "",
        "Generated by `python profile.py` (read-only). Every number below is recomputed",
        "from the database on each run; nothing is quoted from the data dictionary,",
        "which itself warns that some of its descriptions are wrong.",
        "",
    ]
    for title, meaning, evidence in findings:
        lines_md += [f"## {title}", "", meaning, "", f"> **Evidence:** {evidence}", ""]
    OUT.write_text("\n".join(lines_md), encoding="utf-8")
    print(f"Wrote {OUT} with {len(findings)} findings.")


if __name__ == "__main__":
    main()
